using DigiMenu.Api.Data; using DigiMenu.Api.DTOs; using DigiMenu.Api.Domain; using DigiMenu.Api.Services; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using QRCoder;
namespace DigiMenu.Api.Controllers;
[ApiController][Route("api/admin")][Authorize(Policy="RequireBusinessAccess")] public class AdminController(DigiMenuDbContext db,IBusinessAccess access,IPdfService pdf,IFileStorage storage):ControllerBase { async Task<Guid> Business()=>await access.CurrentBusinessId(User); [HttpGet("categories")] public async Task<IResult> Categories(){var id=await Business();return Results.Ok(await db.Categories.Where(x=>x.BusinessID==id).OrderBy(x=>x.DisplayOrder).ToListAsync());} [HttpPost("categories")] public async Task<IResult> AddCategory(CategoryRequest input){var id=await Business();var entity=new Category{Id=Guid.NewGuid(),BusinessID=id,Name=input.Name.Trim(),Description=input.Description,DisplayOrder=input.DisplayOrder,IsActive=input.IsActive};db.Categories.Add(entity);await db.SaveChangesAsync();return Results.Created($"api/admin/categories/{entity.Id}",entity);} [HttpPut("categories/{categoryId:guid}")] public async Task<IResult> EditCategory(Guid categoryId,CategoryRequest input){var id=await Business();var c=await db.Categories.SingleOrDefaultAsync(x=>x.Id==categoryId&&x.BusinessID==id);if(c is null)return Results.NotFound();c.Name=input.Name.Trim();c.Description=input.Description;c.DisplayOrder=input.DisplayOrder;c.IsActive=input.IsActive;c.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Results.Ok(c);} [HttpDelete("categories/{categoryId:guid}")] public async Task<IResult> DeleteCategory(Guid categoryId){var id=await Business();var c=await db.Categories.SingleOrDefaultAsync(x=>x.Id==categoryId&&x.BusinessID==id);if(c is null)return Results.NotFound();c.IsActive=false;c.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Results.NoContent();} [HttpPost("categories/reorder")] public async Task<IResult> ReorderCategories(List<ReorderItem> items){var id=await Business();var cats=await db.Categories.Where(x=>x.BusinessID==id&&items.Select(i=>i.Id).Contains(x.Id)).ToListAsync();foreach(var c in cats)c.DisplayOrder=items.Single(i=>i.Id==c.Id).DisplayOrder;await db.SaveChangesAsync();return Results.NoContent();}
[HttpGet("products")] public async Task<IResult> Products(){var id=await Business();return Results.Ok(await db.Products.Where(x=>x.BusinessID==id).OrderBy(x=>x.CategoryId).ThenBy(x=>x.DisplayOrder).ToListAsync());} [HttpPost("products")] public async Task<IResult> AddProduct(ProductRequest input){var id=await Business();if(!await db.Categories.AnyAsync(x=>x.Id==input.CategoryId&&x.BusinessID==id))return Results.BadRequest(new{message="La categoría no pertenece al negocio activo."});var p=new Product{Id=Guid.NewGuid(),BusinessID=id,CategoryId=input.CategoryId,Name=input.Name.Trim(),Description=input.Description,Price=input.Price,DisplayOrder=input.DisplayOrder,IsActive=input.IsActive,IsAvailable=input.IsAvailable};db.Products.Add(p);await db.SaveChangesAsync();return Results.Created($"api/admin/products/{p.Id}",p);} [HttpPut("products/{productId:guid}")] public async Task<IResult> EditProduct(Guid productId,ProductRequest input){var id=await Business();var p=await db.Products.SingleOrDefaultAsync(x=>x.Id==productId&&x.BusinessID==id);if(p is null)return Results.NotFound();if(!await db.Categories.AnyAsync(x=>x.Id==input.CategoryId&&x.BusinessID==id))return Results.BadRequest();p.CategoryId=input.CategoryId;p.Name=input.Name.Trim();p.Description=input.Description;p.Price=input.Price;p.DisplayOrder=input.DisplayOrder;p.IsActive=input.IsActive;p.IsAvailable=input.IsAvailable;p.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Results.Ok(p);} [HttpDelete("products/{productId:guid}")] public async Task<IResult> DeleteProduct(Guid productId){var id=await Business();var p=await db.Products.SingleOrDefaultAsync(x=>x.Id==productId&&x.BusinessID==id);if(p is null)return Results.NotFound();p.IsActive=false;p.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Results.NoContent();} [HttpPatch("products/{productId:guid}/availability")] public async Task<IResult> Availability(Guid productId,AvailabilityRequest input){var id=await Business();var p=await db.Products.SingleOrDefaultAsync(x=>x.Id==productId&&x.BusinessID==id);if(p is null)return Results.NotFound();p.IsAvailable=input.IsAvailable;await db.SaveChangesAsync();return Results.Ok(p);}
[HttpGet("pdf/current")] public async Task<IResult> CurrentPdf(){var id=await Business();return Results.Ok(await db.BusinessPdfDocuments.Where(x=>x.BusinessID==id&&x.Status==DocumentStatus.Published).OrderByDescending(x=>x.Version).FirstOrDefaultAsync());} [HttpGet("pdf/history")] public async Task<IResult> PdfHistory(){var id=await Business();return Results.Ok(await db.BusinessPdfDocuments.Where(x=>x.BusinessID==id).OrderByDescending(x=>x.Version).ToListAsync());} [HttpPost("pdf/upload")] [RequestSizeLimit(15_000_000)] public async Task<IResult> UploadPdf(IFormFile file){var id=await Business();if(file.Length==0||file.Length>15_000_000||!string.Equals(Path.GetExtension(file.FileName),".pdf",StringComparison.OrdinalIgnoreCase)||file.ContentType!="application/pdf")return Results.BadRequest(new{message="Solo se aceptan PDF de máximo 15 MB."});var key=await storage.SaveAsync(file.OpenReadStream(),file.FileName,file.ContentType,HttpContext.RequestAborted);var version=(await db.BusinessPdfDocuments.Where(x=>x.BusinessID==id).MaxAsync(x=>(int?)x.Version)??0)+1;var entity=new BusinessPdfDocument{Id=Guid.NewGuid(),BusinessID=id,Version=version,FileUrl=key,OriginalFileName=Path.GetFileName(file.FileName),SourceType=DocumentSourceType.Uploaded,FileSize=file.Length,CreatedByUserId=access.UserId(User)};db.BusinessPdfDocuments.Add(entity);await db.SaveChangesAsync();return Results.Ok(entity);} [HttpPost("pdf/generate")] [RequestSizeLimit(20_000_000)] public async Task<IResult> GeneratePdf(IFormFile? headerBackground, IFormFile? innerBackground){try{var id=await Business();string? headerKey=null;string? innerKey=null;if(headerBackground is not null){if(!ValidBackground(headerBackground))return Results.BadRequest(new{message="El fondo del encabezado debe ser PNG, JPG o WebP de hasta 10 MB."});headerKey=await storage.SaveAsync(headerBackground.OpenReadStream(),$"{id:N}-draft-header{Path.GetExtension(headerBackground.FileName)}",headerBackground.ContentType,HttpContext.RequestAborted);}if(innerBackground is not null){if(!ValidBackground(innerBackground))return Results.BadRequest(new{message="El fondo interior debe ser PNG, JPG o WebP de hasta 10 MB."});innerKey=await storage.SaveAsync(innerBackground.OpenReadStream(),$"{id:N}-draft-interior{Path.GetExtension(innerBackground.FileName)}",innerBackground.ContentType,HttpContext.RequestAborted);}return Results.Ok(await pdf.GenerateDraftAsync(id,access.UserId(User),HttpContext.RequestAborted,headerKey,innerKey));}catch(InvalidOperationException e){return Results.BadRequest(new{message=e.Message});}} [HttpPost("pdf/{documentId:guid}/publish")] public async Task<IResult> Publish(Guid documentId){try{await pdf.PublishAsync(await Business(),documentId,access.UserId(User),HttpContext.RequestAborted);return Results.NoContent();}catch(KeyNotFoundException){return Results.NotFound();}catch(InvalidOperationException e){return Results.BadRequest(new{message=e.Message});}}
[HttpPost("qr/generate")] public async Task<IResult> Qr(QrRequest input){var id=await Business();var business=await db.Businesses.SingleAsync(x=>x.Id==id);var dest=input.Destination is "Pdf" or "Animated"?input.Destination:"Main";if(dest=="Animated"&&!business.HasAnimatedMenu)return Results.BadRequest(new{message="El menú animado no está habilitado."});var suffix=dest=="Main"?"":$"/{dest.ToLowerInvariant()}";var url=$"{Request.Scheme}://{Request.Host}/{business.Slug}{suffix}";var config=await db.QrConfigurations.SingleOrDefaultAsync(x=>x.BusinessID==id)??new QrConfiguration{Id=Guid.NewGuid(),BusinessID=id};config.DefaultDestination=dest;config.LastGeneratedUrl=url;config.UpdatedAt=DateTime.UtcNow;db.Update(config);await db.SaveChangesAsync();return Results.Ok(new{url,fileName=$"{business.Slug}-{dest.ToLowerInvariant()}-qr",downloadUrl=$"/api/admin/qr/download?destination={dest}&format={input.Format}"});}

[HttpGet("qr/download")]
public async Task<IResult> DownloadQr([FromQuery]string destination="Main",[FromQuery]string format="svg",[FromQuery]int size=1024,[FromQuery]string foreground="#171a2f",[FromQuery]string background="#ffffff")
{
    if (size is not (512 or 1024 or 2048)) return Results.BadRequest(new { message = "Elige un tamaño de 512, 1024 o 2048 px." });
    if (!TryColor(foreground, out var dark) || !TryColor(background, out var light)) return Results.BadRequest(new { message = "Usa colores hexadecimales de seis dígitos." });
    if (ContrastRatio(dark, light) < 4.5) return Results.BadRequest(new { message = "El contraste entre el código y el fondo debe ser mayor para que se pueda escanear." });

    var id=await Business(); var business=await db.Businesses.SingleAsync(x=>x.Id==id); var dest=destination is "Pdf" or "Animated"?destination:"Main";
    if(dest=="Animated"&&!business.HasAnimatedMenu)return Results.BadRequest();
    var url=$"{Request.Scheme}://{Request.Host}/{business.Slug}{(dest=="Main"?"":$"/{dest.ToLowerInvariant()}")}";
    using var generator=new QRCodeGenerator(); using var data=generator.CreateQrCode(url,QRCodeGenerator.ECCLevel.Q);
    var pixelsPerModule=Math.Max(1,size/data.ModuleMatrix.Count); var name=$"{business.Slug}-{dest.ToLowerInvariant()}-{size}px-qr";
    if(format.Equals("png",StringComparison.OrdinalIgnoreCase))
    {
        var png=new PngByteQRCode(data).GetGraphic(pixelsPerModule, ToRgba(dark), ToRgba(light));
        return Results.File(png,"image/png",$"{name}.png");
    }
    var svg=new SvgQRCode(data).GetGraphic(pixelsPerModule, foreground, background);
    return Results.File(System.Text.Encoding.UTF8.GetBytes(svg),"image/svg+xml",$"{name}.svg");
}

static bool TryColor(string value,out string hex){hex=(value??string.Empty).Trim();if(!hex.StartsWith('#'))hex="#"+hex;return System.Text.RegularExpressions.Regex.IsMatch(hex,"^#[0-9A-Fa-f]{6}$");}
static byte[] ToRgba(string hex)=>[Convert.ToByte(hex[1..3],16),Convert.ToByte(hex[3..5],16),Convert.ToByte(hex[5..7],16),255];
static double ContrastRatio(string first,string second){static double L(string hex){var c=ToRgba(hex).Take(3).Select(x=>x/255d).Select(x=>x<=.04045?x/12.92:Math.Pow((x+.055)/1.055,2.4)).ToArray();return .2126*c[0]+.7152*c[1]+.0722*c[2];}var a=L(first);var b=L(second);return (Math.Max(a,b)+.05)/(Math.Min(a,b)+.05);}
static bool ValidBackground(IFormFile file)=>file.Length>0&&file.Length<=10_000_000&&new[]{"image/png","image/jpeg","image/webp"}.Contains(file.ContentType,StringComparer.OrdinalIgnoreCase);
}
