namespace DigiMenu.Api.Domain;
public enum Role { Superadmin, BusinessAdmin }
public enum PublicMenuMode { Pdf, Animated }
public enum DocumentSourceType { Uploaded, Generated }
public enum DocumentStatus { Draft, Published, Archived }
public enum TemplateStatus { Draft, NeedsReview, Approved, Rejected, Archived }
public enum AnalysisStatus { Pending, Processing, NeedsReview, Approved, Rejected, Failed }
public class Business { public Guid Id{get;set;} public required string Name{get;set;} public required string Slug{get;set;} public string? BusinessType{get;set;} public string? Address{get;set;} public string? Description{get;set;} public string? OpeningHours{get;set;} public string? Phone{get;set;} public string? Email{get;set;} public string? LogoUrl{get;set;} public bool IsActive{get;set;}=true; public PublicMenuMode PublicMenuMode{get;set;}=PublicMenuMode.Pdf; public bool HasAnimatedMenu{get;set;} public string? AnimatedMenuKey{get;set;} public Guid? PublishedPdfDocumentId{get;set;} public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public DateTime UpdatedAt{get;set;}=DateTime.UtcNow; public List<Category> Categories{get;set;}=[]; }
public class AppUser { public Guid Id{get;set;} public required string Email{get;set;} public required string PasswordHash{get;set;} public string? DisplayName{get;set;} public bool IsActive{get;set;}=true; public List<UserBusiness> UserBusinesses{get;set;}=[]; }
public class UserBusiness { public Guid Id{get;set;} public Guid UserId{get;set;} public Guid BusinessID{get;set;} public Role Role{get;set;} public bool IsActive{get;set;}=true; public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public AppUser User{get;set;}=null!; public Business Business{get;set;}=null!; }
public class Category { public Guid Id{get;set;} public Guid BusinessID{get;set;} public required string Name{get;set;} public string? Description{get;set;} public int DisplayOrder{get;set;} public bool IsActive{get;set;}=true; public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public DateTime UpdatedAt{get;set;}=DateTime.UtcNow; public List<Product> Products{get;set;}=[]; }
public class Product { public Guid Id{get;set;} public Guid BusinessID{get;set;} public Guid CategoryId{get;set;} public required string Name{get;set;} public string? Description{get;set;} public decimal Price{get;set;} public int DisplayOrder{get;set;} public bool IsActive{get;set;}=true; public bool IsAvailable{get;set;}=true; public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public DateTime UpdatedAt{get;set;}=DateTime.UtcNow; public Category Category{get;set;}=null!; }
public class BusinessPdfTemplate { public Guid Id{get;set;} public Guid BusinessID{get;set;} public required string Name{get;set;} public TemplateStatus Status{get;set;} public string PageSize{get;set;}="A4"; public string Orientation{get;set;}="Portrait"; public string? CoverBackgroundUrl{get;set;} public string? InnerPageBackgroundUrl{get;set;} public required string LayoutConfigurationJson{get;set;}="{}"; public string TypographyConfigurationJson{get;set;}="{}"; public string ColorConfigurationJson{get;set;}="{}"; public string DecorationConfigurationJson{get;set;}="{}"; public bool CreatedFromAI{get;set;} public bool IsActive{get;set;} public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public DateTime UpdatedAt{get;set;}=DateTime.UtcNow; public DateTime? ApprovedAt{get;set;} public Guid? ApprovedByUserId{get;set;} }
public class BusinessPdfFont { public Guid Id{get;set;} public Guid BusinessID{get;set;} public required string Name{get;set;} public required string FileUrl{get;set;} public bool IsActive{get;set;} public DateTime CreatedAt{get;set;}=DateTime.UtcNow; }
public class BusinessPdfDocument { public Guid Id{get;set;} public Guid BusinessID{get;set;} public int Version{get;set;} public required string FileUrl{get;set;} public required string OriginalFileName{get;set;} public DocumentSourceType SourceType{get;set;} public DocumentStatus Status{get;set;}=DocumentStatus.Draft; public long FileSize{get;set;} public string MimeType{get;set;}="application/pdf"; public Guid CreatedByUserId{get;set;} public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public DateTime? PublishedAt{get;set;} public DateTime? ArchivedAt{get;set;} }
public class PdfTemplateAnalysis { public Guid Id{get;set;} public Guid BusinessID{get;set;} public required string SourceFileUrl{get;set;} public AnalysisStatus Status{get;set;}=AnalysisStatus.Pending; public string? ExtractedContentJson{get;set;} public string? DetectedLayoutJson{get;set;} public string? SuggestedTemplateJson{get;set;} public decimal? ConfidenceScore{get;set;} public string? Provider{get;set;} public string? Model{get;set;} public string? ErrorMessage{get;set;} public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public DateTime? CompletedAt{get;set;} public DateTime? ReviewedAt{get;set;} public Guid? ReviewedByUserId{get;set;} }
public class QrConfiguration { public Guid Id{get;set;} public Guid BusinessID{get;set;} public string DefaultDestination{get;set;}="Main"; public string? LastGeneratedUrl{get;set;} public DateTime UpdatedAt{get;set;}=DateTime.UtcNow; }
public class AuditLog { public Guid Id{get;set;} public Guid? UserId{get;set;} public Guid? BusinessID{get;set;} public required string Action{get;set;} public required string EntityType{get;set;} public string? EntityId{get;set;} public string? PreviousValuesJson{get;set;} public string? NewValuesJson{get;set;} public DateTime CreatedAt{get;set;}=DateTime.UtcNow; }
public class RefreshToken { public Guid Id{get;set;} public Guid UserId{get;set;} public required string TokenHash{get;set;} public DateTime ExpiresAt{get;set;} public DateTime CreatedAt{get;set;}=DateTime.UtcNow; public DateTime? RevokedAt{get;set;} public AppUser User{get;set;}=null!; }
